import yaml from 'js-yaml';
import { Action, Floor, Marker, Project } from '../model/schema';
import { ExportOptions, imageHref } from './svg';

export interface PictureElementsResult {
  yaml: string;
  roomsSkipped: number;
}

function toHaAction(a: Action | undefined): unknown {
  if (!a || a.kind === 'none') return { action: 'none' };
  switch (a.kind) {
    case 'toggle':
      return { action: 'toggle' };
    case 'more-info':
      return { action: 'more-info' };
    case 'call-service': {
      let data: unknown = undefined;
      if (a.serviceData) {
        try {
          data = yaml.load(a.serviceData);
        } catch {
          /* ignore */
        }
      }
      return { action: 'call-service', service: a.service, data };
    }
    case 'navigate':
      return { action: 'navigate', navigation_path: a.navPath };
    case 'url':
      return { action: 'url', url_path: a.url };
  }
}

function pct(v: number, total: number): string {
  return `${Math.round((v / total) * 10000) / 100}%`;
}

function elementFor(m: Marker, floor: Floor): Record<string, unknown> | null {
  const entity = m.entities[0];
  if (!entity) return null;
  const style: Record<string, string> = {
    top: pct(m.y, floor.canvas.height),
    left: pct(m.x, floor.canvas.width),
    transform: 'translate(-50%, -50%)',
  };
  const useLabel = m.style.type === 'label' || m.style.showState;
  if (useLabel) {
    // HA state-label honours CSS in the style dict.
    if (m.style.fontFamily) style['font-family'] = m.style.fontFamily;
    if (m.style.fontSize != null) style['font-size'] = `${m.style.fontSize}px`;
    if (m.style.fontWeight != null) style['font-weight'] = String(m.style.fontWeight);
    if (m.style.fontColor) style.color = m.style.fontColor;
  }
  const el: Record<string, unknown> = {
    type: useLabel ? 'state-label' : 'state-icon',
    entity,
    style,
  };
  if (!useLabel && m.style.type === 'icon' && m.style.icon) el.icon = `mdi:${m.style.icon}`;
  const tap = toHaAction(m.actions.tap);
  if (tap) el.tap_action = tap;
  const hold = toHaAction(m.actions.hold);
  if (hold && m.actions.hold.kind !== 'none') el.hold_action = hold;
  const dbl = toHaAction(m.actions.double);
  if (dbl && m.actions.double.kind !== 'none') el.double_tap_action = dbl;

  // conditional visibility -> wrap in a conditional element
  if (m.visibility?.entityId) {
    return {
      type: 'conditional',
      conditions: [
        m.visibility.state
          ? { entity: m.visibility.entityId, state: m.visibility.state }
          : { entity: m.visibility.entityId, state: 'on' },
      ],
      elements: [el],
    };
  }
  return el;
}

export function buildPictureElements(
  _project: Project,
  floor: Floor,
  opts: ExportOptions,
): PictureElementsResult {
  const elements: unknown[] = [];
  for (const m of floor.markers) {
    const el = elementFor(m, floor);
    if (el) elements.push(el);
  }

  const card = {
    type: 'picture-elements',
    image: imageHref(floor, opts),
    elements,
  };

  const header =
    `# picture-elements card generated by Floorplan Studio\n` +
    `# Native Home Assistant card — no custom dependencies required.\n` +
    (floor.rooms.length
      ? `# NOTE: ${floor.rooms.length} polygon room(s) were NOT exported — picture-elements\n` +
        `#       can't render filled polygons. Use the ha-floorplan target for rooms.\n`
      : '') +
    (opts.image === 'reference'
      ? `# Reference mode: copy ${opts.imageBaseName}.png into /config/www/${opts.localDir}/\n`
      : `# Embed mode: image inlined as a data URI.\n`);

  return {
    yaml: header + yaml.dump(card, { lineWidth: -1, noRefs: true }),
    roomsSkipped: floor.rooms.length,
  };
}
